### ISSUE TITLE
自律计划

### ISSUE THREAD

**Issue by webproblem** [webproblem/Blog#11]
受 ScarSu 小姐姐的自律计划的启发，同时也意思到自己的不自律，执行力不够，所以也试着开始养成自律的习惯，希望能够坚持下去。

据说我们要养成一个习惯，至少需要21天的坚持。 所以这里制定的自律计划的时间范围是 2018.11.19-2018.12.16，大概是一个月左右的时间，如果能坚持下去，后面的自律计划会适当调整。

### 每日打卡项

* 早起
* 早餐
* 学习
* 运动
* 每日总结整理
* 控制睡前刷手机
* 睡觉

#### 早起

一日之计在于晨，坚持早起同时也意味着能坚持按时睡觉。早起空闲出来的时间可以做很多事情，学习，运动，思考等。

#### 早餐

平时周末有不吃早餐的习惯，其实这样长期对身体不好，所以要坚持吃早餐且要有营养。

#### 学习

学习又分为软技能和专业技能，软技能包括很多方面，主要是对自己认知和思维上的提升，包括学英语，看书，听电台等一些有营养的提升方式，专业技能指的是工作方面的提升。保证每天至少有3小时的时间花在学习上。

#### 运动

坚持运动，锻炼身体是很有必要的，每天抽出1小时的时间来运动，包括慢跑或快走等。

#### 每日总结整理

之前就有过这样的动作，但很多都是断断续续的，并没有坚持每天去梳理总结。所以要养成每天总结的习惯，反思自己不断进步，同时也记录生活的而点滴。

#### 控制睡前刷手机

睡前玩手机容易影响睡眠，睡前应该保持一个舒适的状态，所以睡前半小时不能玩手机。

#### 睡觉

要做到早起，就必须要有规律的按时入睡，才能保证一天良好的状态。

#### 早起

早上 6:50 起床

7:20-8:20 学习

#### 早餐

9:00 之前完成

#### 学习

早上1小时，19:00-20:00 1小时，21:30-22:10，其他碎片化时间

#### 运动

20:10-21:00，方式主要是慢跑或者快走

#### 每日总结整理

22:30 之前完成

#### 睡觉

23:00 之前手机关机，23:20 之前入睡

### 打卡表（日更）

| 日期       | 早起 | 早餐 | 学习   | 运动   | 每日总结整理 | 控制睡前刷手机 | 睡觉   |
| ---------- | ---- | ---- | ------ | ------ | ------------ | -------------- | ------ |
| 2018.11.19 | 完成 | 完成 | 完成   | 未完成 | 完成         | 未完成         | 完成   |
| 2018.11.20 | 完成 | 完成 | 未完成 | 完成   | 完成         | 未完成         | 未完成 |
| 2018.11.21 |      |      |        |        |              |                |        |
| 2018.11.22 |      |      |        |        |              |                |        |
| 2018.11.23 |      |      |        |        |              |                |        |
| 2018.11.24 |      |      |        |        |              |                |        |
| 2018.11.25 |      |      |        |        |              |                |        |
| 2018.11.26 |      |      |        |        |              |                |        |
| 2018.11.27 |      |      |        |        |              |                |        |
| 2018.11.28 |      |      |        |        |              |                |        |
| 2018.11.29 |      |      |        |        |              |                |        |
| 2018.11.30 |      |      |        |        |              |                |        |
| 2018.12.01 |      |      |        |        |              |                |        |
| 2018.12.02 |      |      |        |        |              |                |        |
| 2018.12.03 |      |      |        |        |              |                |        |
| 2018.12.04 |      |      |        |        |              |                |        |
| 2018.12.05 |      |      |        |        |              |                |        |
| 2018.12.06 |      |      |        |        |              |                |        |
| 2018.12.07 |      |      |        |        |              |                |        |
| 2018.12.08 |      |      |        |        |              |                |        |
| 2018.12.09 |      |      |        |        |              |                |        |
| 2018.12.10 |      |      |        |        |              |                |        |
| 2018.12.11 |      |      |        |        |              |                |        |
| 2018.12.12 |      |      |        |        |              |                |        |
| 2018.12.13 |      |      |        |        |              |                |        |
| 2018.12.14 |      |      |        |        |              |                |        |
| 2018.12.15 |      |      |        |        |              |                |        |
| 2018.12.16 |      |      |        |        |              |                |        |

**Comment by scarsu** [comment]
怎么不更新了，坚持完12月也不错哦

**Comment by webproblem** [comment]
> 怎么不更新了，坚持完12月也不错哦

哈哈，都改在本地电脑更新了，到时候统一更新上去

**Comment by webproblem** [comment]
> 怎么不更新了，坚持完12月也不错哦
哈哈，都在本地电脑更新了，到时候统一更新上去

**Comment by scarsu** [comment]
> > 怎么不更新了，坚持完12月也不错哦
> > 哈哈，都在本地电脑更新了，到时候统一更新上去

棒(๑•̀ㅂ•́)و✧
